# Generated by Django 5.2.3 on 2025-07-30 13:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("country", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Cities",
            },
        ),
        migrations.CreateModel(
            name="Weather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.FloatField(help_text="Temperature in Celsius")),
                (
                    "humidity",
                    models.IntegerField(
                        help_text="Humidity",
                        validators=[
                            django.core.validators.MinLengthValidator(0),
                            django.core.validators.MaxLengthValidator(100),
                        ],
                    ),
                ),
                ("wind_speed", models.FloatField(help_text="Wind Speed m/s")),
                ("pressure", models.IntegerField(help_text="Pressure hPa")),
                (
                    "brief_description",
                    models.CharField(
                        help_text="Brief Description of current city weather",
                        max_length=500,
                    ),
                ),
                ("record_at", models.DateTimeField(auto_now_add=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_records",
                        to="weather.city",
                    ),
                ),
            ],
            options={
                "ordering": ["-record_at"],
            },
        ),
    ]
